# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 05:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name=datetime.datetime(2018, 1, 16, 10, 40, 32, 337764))),
            ],
        ),
    ]
